[2022-02-13 03:43:05,137] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_workflow.test_function scheduled__2022-02-11T00:00:00+00:00 [queued]>
[2022-02-13 03:43:05,551] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_workflow.test_function scheduled__2022-02-11T00:00:00+00:00 [queued]>
[2022-02-13 03:43:05,582] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-13 03:43:05,596] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-13 03:43:05,608] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-13 03:43:06,149] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): test_function> on 2022-02-11 00:00:00+00:00
[2022-02-13 03:43:06,286] {standard_task_runner.py:52} INFO - Started process 115 to run task
[2022-02-13 03:43:06,349] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test_workflow', 'test_function', 'scheduled__2022-02-11T00:00:00+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/test_workflow.py', '--cfg-path', '/tmp/tmp8ywod4t6', '--error-file', '/tmp/tmpbgsrqlov']
[2022-02-13 03:43:06,351] {standard_task_runner.py:77} INFO - Job 112: Subtask test_function
[2022-02-13 03:43:07,867] {logging_mixin.py:109} INFO - Running <TaskInstance: test_workflow.test_function scheduled__2022-02-11T00:00:00+00:00 [running]> on host c762f4aacf84
[2022-02-13 03:43:09,026] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_workflow
AIRFLOW_CTX_TASK_ID=test_function
AIRFLOW_CTX_EXECUTION_DATE=2022-02-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-11T00:00:00+00:00
[2022-02-13 03:43:09,053] {python.py:175} INFO - Done. Returned value was: None
[2022-02-13 03:43:11,420] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=test_workflow, task_id=test_function, execution_date=20220211T000000, start_date=20220213T034305, end_date=20220213T034311
[2022-02-13 03:43:11,689] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-13 03:43:12,024] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
